# Generated by Django 3.1.5 on 2021-02-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author_name',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
